apiVersion: apps.wandb.com/v2
kind: WeightsAndBiases
metadata:
  name: wandb-dev-v2
spec:
  size: dev
  mysql:
    enabled: true
    storageSize: 5Gi
  redis:
    enabled: true
    storageSize: 1Gi
  kafka:
    enabled: true
    storageSize: 10Gi
    replicas: 1
    backup:
      enabled: true
      storageName: default-backup
      storageType: filesystem
      filesystem:
        storageSize: 5Gi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
      timeoutSeconds: 600
  minio:
    enabled: true
    storageSize: 10Gi
    replicas: 1
  clickhouse:
    enabled: true
    storageSize: 10Gi
    replicas: 1