apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-mysql
rules:
  - apiGroups:
      - mysql.oracle.com
    resources:
      - innodbclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mysql.oracle.com
    resources:
      - innodbclusters/status
    verbs:
      - get
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-mysql
subjects:
  - kind: ServiceAccount
    name: wandb-operator
    namespace: {{ .Release.Namespace }}
