---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert
  name: {{ .Release.Name }}-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: wandb-operator
        namespace: {{ .Release.Namespace }}
        path: /mutate-apps-wandb-com-v2-application
    failurePolicy: Fail
    name: mapplication-v2.kb.io
    rules:
      - apiGroups:
          - apps.wandb.com
        apiVersions:
          - v2
        operations:
          - CREATE
          - UPDATE
        resources:
          - applications
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: wandb-operator
        namespace: {{ .Release.Namespace }}
        path: /mutate-apps-wandb-com-v2-weightsandbiases
    failurePolicy: Fail
    name: mweightsandbiases-v2.kb.io
    rules:
      - apiGroups:
          - apps.wandb.com
        apiVersions:
          - v2
        operations:
          - CREATE
          - UPDATE
        resources:
          - weightsandbiases
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert
  name: {{ .Release.Name }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: wandb-operator
        namespace: {{ .Release.Namespace }}
        path: /validate-apps-wandb-com-v2-application
    failurePolicy: Fail
    name: vapplication-v2.kb.io
    rules:
      - apiGroups:
          - apps.wandb.com
        apiVersions:
          - v2
        operations:
          - CREATE
          - UPDATE
        resources:
          - applications
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: wandb-operator
        namespace: {{ .Release.Namespace }}
        path: /validate-apps-wandb-com-v2-weightsandbiases
    failurePolicy: Fail
    name: vweightsandbiases-v2.kb.io
    rules:
      - apiGroups:
          - apps.wandb.com
        apiVersions:
          - v2
        operations:
          - CREATE
          - UPDATE
        resources:
          - weightsandbiases
    sideEffects: None
