name: Internal Chart Publish

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3.0.1

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          create_credentials_file: 'true'
          token_format: access_token
          project_id: wandb-production
          workload_identity_provider: ${{ secrets.CI_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CI_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - name: Authorize Docker to use Google Container Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.14.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config deploy/ct.yaml || true)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing  (lint)
        run: ct lint --config deploy/ct.yaml

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Build and Push to GAR
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          VERSION=$(grep "^version:" deploy/operator/Chart.yaml | awk '{print $2}')
          helm dependency build deploy/operator
          helm package deploy/operator
          helm push operator-${VERSION}.tgz oci://$REPOSITORY
        env:
          REPOSITORY: us-docker.pkg.dev/wandb-production/public/wandb/charts
